[book]
authors = ["Jeff Mendez"]
language = "en"
src = "src"
title = "spider-rs"

[output.html]
git-repository-url = "https://github.com/spider-rs/spider-nodejs/tree/main/book"
edit-url-template  = "https://github.com/spider-rs/spider-nodejs/edit/main/book/{path}"
